runtime: nodejs12

handlers:
- url: /.*
  script: auto
  secure: always
  redirect_http_response_code: 301


env_variables:
  MONGOENDPOINT: "mongodb+srv://rom:rom@cluster0-mbq3n.mongodb.net/movie-shop?retryWrites=true"
  ADMIN_USER: "admin@movie-shop.com"
  AUDIENCE: "https://movie-shop-backend"
  ISSUER: "https://movie-shop.us.auth0.com/"
  JWKS_URI: "https://movie-shop.us.auth0.com/.well-known/jwks.json"